Garage.Assistant.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Garage.Assistant.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Garage.Assistant.Web/Controllers/InventoryController.cs
using Garage.Assistant.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Garage.Assistant.Web.Controllers
{
    public class InventoryController : BaseController
    {


        private static List<Product> _products = new List<Product>()
        {
              new Product(1, "Spanner", "Size 4 Spanner", 4, true, 55m),
                new Product(2, "Wrench", "Adjustable wrench", 2, true, 65.55m),
                new Product(3, "Hammer", "Good for whacking things", 0, false, 77.25m),
                new Product(4, "Jack Lift", "Great for lifting things", 1, true, 44.25m),
                new Product(5, "Spare Tyre", "Goes round", 4, false, 77m)
        };

        // GET: Inventory
        public ActionResult Index()
        {

            return View();
        }


        public ActionResult IndexVM()
        {

            InventoryViewModel model = new InventoryViewModel();
            model.Products = _products;

            return Json(model, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Edit(Product model)
        {

            Thread.Sleep(3000);

            if (ModelState.IsValid)
            {
                if (model.Id == 0 || model.Id == null)
                {
                    _products.Add(model);
                }
                else
                {
                    int index = _products.IndexOf(_products.Single(x => x.Id == model.Id));

                    if (index >= 0)
                    {
                        _products[index] = model;
                    }
                }
            }
            return Json(model, JsonRequestBehavior.AllowGet);
        }


    }
}

Garage.Assistant.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Garage.Assistant.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Garage.Assistant.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Garage Assistant</h1>
</div>


<div class="row">
    <div class="col-md-4">
        <h4>Ipsum.</h4>
        <p>Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.</p>
    </div>
    <div class="col-md-4">
        <h4>Ipsum.</h4>
        <p>Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.</p>
    </div>
    <div class="col-md-4">
        <h4>Ipsum.</h4>
        <p>Volutpat phasellus dapibus arcu sit amet neque vulputate sed elementum orci fringilla in hac habitasse platea dictumst maecenas ut dui diam curabitur adipiscing vestibulum libero, nec varius dui pulvinar eget vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; aliquam dui neque, varius eu laoreet vel.</p>
    </div>
</div>

<hr />


<div class="row">
    <div class="col-md-6">
        <h4>Manage your inventory</h4>
        <p>Justo nunc tempor, metus vel placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis ut vitae feugiat augue cras ut metus a risus iaculis scelerisque eu ac ante fusce non varius purus aenean nec magna felis fusce vestibulum velit mollis odio sollicitudin lacinia aliquam posuere, sapien elementum lobortis.</p>

        <a href="@Url.Action("Index", "Inventory")" class="btn btn-default">
            Go to inventory
        </a>
    </div>
</div>